title: Chez Papizz
author:
  name: Tom
  email: 'contact@chez-papizz.fr'
metadata:
    description: 'Pizza, Burgers et Salades à emporter et maison'

# Site settings
title: Chez Papizz | Pizza, Burgers et Salades | Cugnaux
email: contact@chez-papizz.fr
description: "Pizza, Burgers et Salades à emporter sur Cugnaux"

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Services
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Team
    url: '#team'
  - title: Contact
    url: '#contact'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'
